on:
  push:
    branches:
    - master
    
name: OpenAPI Specs lint

jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Spectral checks
        uses: XVincentX/spectral-action@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_TOKEN }}
          SPECTRAL_FILE_PATH: ./*/*.json
